import { create } from 'zustand';
import { AIRCRAFT, defaultAircraft, type Aircraft } from '../data/aircraft';
import { MISSIONS, WEATHER, type WeatherPreset } from '../data/world';

export type SimPhase='Preflight'|'Taxi'|'Takeoff'|'Climb'|'Cruise'|'Descent'|'Approach'|'Landed'|'Crashed';
export type Telemetry={ias:number;altitude:number;verticalSpeed:number;heading:number;throttle:number;fuelPct:number;pitch:number;roll:number;gLoad:number;gearDown:boolean;flaps:number;phase:SimPhase;score:number;stall:boolean;overspeed:boolean;onGround:boolean;wind:string;atc:string;traffic:number;rank:string;mission:string;aircraft:string;camera:string};
type SimStore={aircraft:Aircraft;weather:WeatherPreset;missionIndex:number;started:boolean;paused:boolean;telemetry:Telemetry;selectAircraft:(id:string)=>void;selectWeather:(id:string)=>void;selectMission:(index:number)=>void;start:()=>void;pause:()=>void;updateTelemetry:(patch:Partial<Telemetry>)=>void;resetSession:()=>void};
const baseTelemetry:Telemetry={ias:0,altitude:7,verticalSpeed:0,heading:90,throttle:0,fuelPct:100,pitch:0,roll:0,gLoad:1,gearDown:true,flaps:0,phase:'Preflight',score:100,stall:false,overspeed:false,onGround:true,wind:'270/12',atc:'Clearance: cleared to Boston via MERIT departure, climb 5,000.',traffic:12,rank:'Student Pilot',mission:MISSIONS[0].type,aircraft:defaultAircraft.name,camera:'Chase'};
export const useSimStore=create<SimStore>((set,get)=>({aircraft:defaultAircraft,weather:WEATHER[0],missionIndex:0,started:false,paused:false,telemetry:baseTelemetry,selectAircraft:(id)=>set(()=>{const aircraft=AIRCRAFT.find(a=>a.id===id)??defaultAircraft;return{aircraft,telemetry:{...get().telemetry,aircraft:aircraft.name}}}),selectWeather:(id)=>set(()=>{const weather=WEATHER.find(w=>w.id===id)??WEATHER[0];return{weather,telemetry:{...get().telemetry,wind:`${weather.windDir}/${weather.windKt}`}}}),selectMission:(missionIndex)=>set(()=>({missionIndex,telemetry:{...get().telemetry,mission:MISSIONS[missionIndex]?.type??MISSIONS[0].type}})),start:()=>set({started:true,paused:false}),pause:()=>set(s=>({paused:!s.paused})),updateTelemetry:(patch)=>set(s=>({telemetry:{...s.telemetry,...patch}})),resetSession:()=>set(s=>({started:false,paused:false,telemetry:{...baseTelemetry,aircraft:s.aircraft.name,mission:MISSIONS[s.missionIndex]?.type??MISSIONS[0].type,wind:`${s.weather.windDir}/${s.weather.windKt}`}}))}));
